### ISSUE TITLE
what is the time complexity of this algrithm? 

### ISSUE THREAD

**Issue by aktiger** [rpmcruz/autoaugment#1]
what is the time complexity of this algrithm?

**Comment by rpmcruz** [comment]
The time complexity is linear: O(n) where n is the number of child models/hyperparameters you want to try. The higher, the better.

Please notice I am not the author of the paper. This is just an implementation of the paper. If you read the paper, you will see that in order to speed things up, the authors train the child models using a reduced dataset and also use few epochs.

Email me if you would like to discuss this further.
